microsoft/krabsetw

- examples/ManagedExamples/KernelTrace001.cs
- examples/NativeExamples/kernel_and_user_trace_001.cpp
- examples/NativeExamples/kernel_trace_001.cpp
Check against opcodes instead of event names in kernel examples. Event names seem to be inconsistently set.
> Fix kernel examples.

- krabs/krabs/filtering/comparers.hpp
- krabs/krabs/filtering/predicates.hpp
- krabs/krabs/schema_locator.hpp
Ensure that comparers.hpp is compiled as unmanaged when /clr is set. This is necessary to ensure that when boost::* makes use of the std::locale lock, we only take the lock on the native side. If the std::locale lock is taken on the managed side, we introduce a loader lock.
Signed-off-by: Zac Brown (ODSP SECURITY) <zbrown@microsoft.com>
> Ensure that comparers.hpp is compiled as unmanaged code.

- krabs/krabs/nightmare.hpp
This fix addresses a misused flag. It happens that the change is net-zero because the new flag has the same value as the originally misused flag:
- EVENT_TRACE_NO_PER_PROCESSOR_BUFFERING = 0x10000000
- PROCESS_TRACE_MODE_EVENT_RECORD = 0x10000000
This addresses https://github.com/Microsoft/krabsetw/issues/39
> Fix mis-used flag.

- O365.Security.Native.ETW/O365.Security.Native.ETW.vcxproj
- examples/NativeExamples/NativeExamples.vcxproj
- krabs/krabs.sln
- krabs/krabs/filtering/comparers.hpp
- krabs/krabs/testing/record_builder.hpp
- krabs/krabs/ut.hpp
- tests/krabstests/krabstests.vcxproj
- tests/krabstests/test_parse_types.cpp
This should address #42 
Tested that examples and tests build with:
* Current default of VS 2015 and SDK 8.1
* VS 2017 15.6.5, SDK 10.0.16299.0 and /permissive-
> Fix errors when building with /permissive- (#42)

- krabs/krabs/parser.hpp
- krabs/krabs/size_provider.hpp
- krabs/krabs/testing/record_builder.hpp
- tests/krabstests/test_parser.cpp
This set introduces two improvements:
1. The properties cache in the parser could store multiple copies of the same property
This situation could occur because the last property parsed was added to the cache and returned but the buffer pointer and property index were not incremented. This is now fixed: every parsed property can exist in the cache just once and there is no duplicate property parsing.
2. String values (ANSI and UNICODE) that belong to the last property in an event record are not guaranteed to be null-terminated. The code assumes that every string is null-terminated, which causes strlen and wcslen to potentially access invalid memory looking for a null terminator. If the memory access succeeds, the parser will throw an exception as the length of the string property will be …
> Improve property parsing

- krabsetw.nuspec
The build uses boost 1.68 but the .nuspec takes a dependency on boost 1.61.
> Update .nuspec dependency to match the dependency in the build

- krabs/krabs/provider.hpp
Fix #71 by adding a `break` statement when the provider is found
> Add early return when finding provider by name

- krabs/krabs/filtering/event_filter.hpp
event_filter.hpp uses `std::vector` but does not contain `#include <vector>` 
This presumably worked previously because one of the existing includes transitively included vector but that is apparently no longer the case.
> Added <vector> include to event_filter.hpp to make it compile on VS2019

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- O365.Security.Native.ETW/Conversions.hpp
- O365.Security.Native.ETW/Filtering/EventFilter.hpp
- O365.Security.Native.ETW/O365.Security.Native.ETW.vcxproj
- O365.Security.Native.ETW/O365.Security.Native.ETW.vcxproj.filters
- examples/ManagedExamples/ManagedExamples.csproj
- examples/ManagedExamples/Program.cs
- examples/ManagedExamples/UserTrace003.cs
- examples/ManagedExamples/UserTrace004.cs
#60 added support for native ETW filtering in krabs `event_filter.hpp`. 
This plumbs support through to `EventFilter.cs` so C++/CLI callers can take advantage of it.
> Add support in C++/CLI for native ETW filtering

- Microsoft.O365.Security.Native.ETW/Errors.hpp
- Microsoft.O365.Security.Native.ETW/KernelTrace.hpp
- krabs/krabs/errors.hpp
- krabs/krabs/etw.hpp
It bugged me that I could get a start_trace_failure before I called start().  ¯\_(ツ)_/¯ 
(This is due to the introduction of open() in https://github.com/microsoft/krabsetw/pull/54).
It just seems cleaner to me to have an open_trace_failure instead...  :-)
> updated exception to reflect decoupling of open() and process()

- Microsoft.O365.Security.Native.ETW/Filtering/Fluent.hpp
- Microsoft.O365.Security.Native.ETW/Kernel/KernelProviders.hpp
- examples/NativeExamples/user_trace_005.cpp
- krabs/krabs/etw.hpp
- krabs/krabs/kernel_providers.hpp
- tests/krabstests/test_user_providers.cpp
In C# I wanted to be able to call .stop() to clean up orphan traces - without having to start processing events.
Originally I planned to add C++/CLI support for .open() which should(?) have worked. But when I dug into it, it seemed neater to just always (blindly) call STOP and swallow any 'not found' status codes. Thoughts?
~~I then also noticed a superfluous call to unregister_trace() and that CloseTrace() was *never* being called.  (See comment on https://github.com/microsoft/krabsetw/pull/82)  So I've proposed a fix for this logic.~~
And finally, I propose renaming unregister_trace() ~~to~~ *and* stop_trace() ~~and vice versa~~.
unregister_trace was calling ControlTrace(STOP) - which is the converse operation to start_trace() *so rename to stop_trace()*
stop_trace was calling …
>   .stop() should always call ControlTrace(STOP) - even if .open()/.start() has not been called

- Microsoft.O365.Security.Native.ETW/KernelTrace.hpp
- Microsoft.O365.Security.Native.ETW/UserTrace.hpp
- krabs/krabs/etw.hpp
- krabs/krabs/trace.hpp
On second though, process() is a bit redundant and could be deprecated.
> deprecate process()

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabsetw.nuspec
- tests/ManagedETWTests/EtwTestsCS.csproj
- Bumped the major version since we've made a change to the public API
- Added `<LangVersion>latest</LangVersion>` where needed to support `ref struct` in C#
> Update Nuget versions to 3.0.0

- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj
Added `krabs` dir to `Microsoft.O365.Security.Native.ETW's AdditionalIneludeDirectories`.
Needed to help support external solutions that wish to build KrabsETW as part of their own build chain, instead of using prebuilt NuGet package. This also enables linking with experimental branches, or when the Nuget Package hasn't been updated to match master.
Without this include the build of `Microsoft.O365.Security.Native.ETW` fails when building it as part of an external solution.
> Added krabs to Native AdditionalIneludeDirectories

- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj
Linked to my Issue related to building KrabsETW Native as part of my own external project: https://github.com/microsoft/krabsetw/issues/101
`$(SolutionDir)...` puts the file outside the codebase, so I'm assuming this was a mistake? `$(ProjectDir)...` seems to make more sence, as that puts it at the project root, where there is the file already existing in the codebase: https://github.com/microsoft/krabsetw/blob/master/35MSSharedLib1024.snk
> PreBuildEvent that was looking for 35MSSharedLib1024.snk in wrong folder

- .github/workflows/krabsetw.yml
- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj
- examples/NativeExamples/NativeExamples.vcxproj
- tests/krabstests/krabstests.vcxproj
The updates to versions was required to make the build work on the github action runners.
The failing test can be fixed by merging #111
> Create github action ci flow

- krabs/krabs/guid.hpp
- krabs/krabs/tdh_helpers.hpp
- krabs/krabs/testing/record_builder.hpp
> Suppress wchar_t to char narrowing when constructing error messages

- Microsoft.O365.Security.Native.ETW/Provider.hpp
- krabs/krabs/provider.hpp
- krabs/krabs/ut.hpp
trace_flags_ is currently a UCHAR, which is a narrower data type than required for some of the new flags specified in evntcons.h for ENABLE_TRACE_PARAMETERS.EnableProperty (which is type ULONG), starting in Windows SDK version 10.0.19041.0. 
This PR widens trace_flags_ to support using the new flags.
> Widen trace_flags_ to ULONG to match ENABLE_TRACE_PARAMETERS.EnableProperty

- Microsoft.O365.Security.Native.ETW/Provider.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/provider.hpp
- krabsetw.nuspec
- tests/krabstests/test_user_providers.cpp
Provider.TraceFlags (and the unmanaged provider::trace_flags) were set-only, this change adds a getter in both places.
> Add getter for property Provider.TraceFlags

- Microsoft.O365.Security.Native.ETW/RawProvider.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabsetw.nuspec
The property works fine, we just need to expose it. :)
Setting nuspec version to 4.1.5 to follow the other PR in the queue, though I'm expecting a merge conflict due to changing the same lines.
> Adds TraceFlags property to RawProvider for parity with Provider.

- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj
- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj.filters
- Microsoft.O365.Security.Native.ETW/packages.config
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- examples/NativeExamples/NativeExamples.vcxproj
- examples/NativeExamples/NativeExamples.vcxproj.filters
- examples/NativeExamples/packages.config
- krabs/krabs/filtering/comparers.hpp
- krabsetw.nuspec
- tests/krabstests/krabstests.vcxproj
- tests/krabstests/krabstests.vcxproj.filters
- tests/krabstests/packages.config
Re-implement four functors in `comparers.hpp` with standard library algorithms in place of Boost algorithms.
> Remove Boost Dependency

- Microsoft.O365.Security.Native.ETW/Errors.hpp
- Microsoft.O365.Security.Native.ETW/EventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/IEventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/Testing/RecordBuilder.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs.sln
- krabs/krabs/guid.hpp
- krabs/krabs/testing/extended_data_builder.hpp
- krabs/krabs/testing/record_builder.hpp
- krabs/krabs/testing/synth_record.hpp
- krabsetw.nuspec
- tests/ManagedETWTests/Events/PowerShellEvent.cs
- tests/ManagedETWTests/describe_EventRecord.cs
- tests/krabstests/krabstests.vcxproj
- tests/krabstests/krabstests.vcxproj.filters
- tests/krabstests/test_guid_parser.cpp
- tests/krabstests/test_record_builder.cpp
This change should allow reading Windows container ID's from events coming from both Provider and RawProvider (from the managed API).
There's an extra #ifdef in extended_data_builder.hpp for compatibility with Windows SDK version 10.0.18362.0.
I will add nuspec version changes once it's clear what the version number should be.
> Read container ID from event extended data

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/perfinfo_groupmask.hpp
- krabsetw.nuspec
A recent change to krabsetw partially defines an enum that is already defined in winternl.h, and it also declares an NT system call that is already declared in winternl.h. Both of these things cause compiler errors in any project which includes krabs.hpp and winternl.h. This PR adds some preprocessor conditionality to avoid defining and declaring if winternl.h has already been included.
> Fix compiler errors when winternl.h is included before krabs.hpp.

- Microsoft.O365.Security.Native.ETW/EventRecord.hpp
- krabs/krabs/parse_types.hpp
- krabs/krabs/parser.hpp
- krabs/krabs/tdh_helpers.hpp
Added ability to parse `TDH_INTYPE_SID` and `TDH_INTYPE_WBEMSID` types.
I made two major assumptions that if you don't agree with I can fix:
1) In `TDH_INTYPE_WBEMSID` we only care about the SID part, not the `TOKEN_USER` - This is based upon this MSDN example, which also only pulls out the SID: https://docs.microsoft.com/en-us/windows/win32/etw/using-tdhgetproperty-to-consume-event-data. Also as this type is depracted, and you're meant to only use `TDH_INTYPE_SID` This meant we can 'decode' both TDHs to the same struct.
2) I store the string of the SID instead of the bytes. As SIDs are variable-length, this seemed like the easiest way to deal with them, as we can have the string on the stack instead of allocating and copying the varaible-length bytes.
> added krabs::sid to parse TDH_INTYPE_SID and TDH_INTYPE_WBEMSID types

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/etw.hpp
- krabs/krabs/trace.hpp
- krabsetw.nuspec
The separate process API allows more fine grained control in multi threaded scenarios as there is no possibility of an implicit opening of the trace.
> Bring back process api for trace

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/perfinfo_groupmask.hpp
- krabs/krabs/schema.hpp
- krabsetw.nuspec
Fixes two things:
1) `event_name` was using at `OpcodeNameOffset` instead of `EventNameOffset`
2) `EventNameOffset` can be 0, in which case it doesn't have an event name
> fixed schema event_name parsing

- Microsoft.O365.Security.Native.ETW/EventRecord.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/parse_types.hpp
- krabs/krabs/parser.hpp
- krabs/krabs/tdh_helpers.hpp
- krabsetw.nuspec
This merge attempts to enable easy parsing of `TDH_INTYPE_POINTER`, whilst attempting to protect developers from poor decisions.
Whilst `TDH_INTYPE_POINTER` are Pointers, the likelihood the address is accessible to the trace process is extremely low, and at times might even be pointers to kernel memory.
As such I feel any solution needs to make it clear to developers using Krabs that while it is OK to get the pointer for printing or comparison purposes, any attempt at de-referencing it will probably blow up in their face.
If we just enable `.parse<void*>()` it as a `void*`, then a dev could blindly do:
```c
std::uint32_t* pFileobj = (std::uint32_t*)parser.parse<void*>(L"FileObject");
// This will either explode (esp. if a kernel pointer), or point to something else entirely
std::uint32_t …
```
> Enable parsing TDH_IN_POINTER types

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- build/native/krabsetw.targets
- krabsetw.nuspec
closes #133 
Right now the [upstream version](https://www.nuget.org/packages/Microsoft.O365.Security.Krabsetw/4.1.12) is broken.
> Remove krabs.cpp reference and add missing header

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/guid.hpp
- krabs/krabs/schema_locator.hpp
- krabs/krabs/testing/record_builder.hpp
- krabsetw.nuspec
- tests/krabstests/krabstests.vcxproj
- tests/krabstests/krabstests.vcxproj.filters
- tests/krabstests/test_guid.cpp
- tests/krabstests/test_parser.cpp
- tests/krabstests/test_schema_key.cpp
> Ignore struct padding when computing std::hash<schema_key> 

- .github/workflows/krabsetw.yml
Ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Fix setup-nuget step in build pipeline

- krabs/krabs/parser.hpp
- krabs/krabs/perfinfo_groupmask.hpp
- krabs/krabs/tdh_helpers.hpp
Exception "Property size doesn't match requested size" rise if we try to query **bool** value from **TDH_INTYPE_BOOLEAN** field.
Example of code:
`if (prop.type() == TDH_INTYPE_BOOLEAN)
val = parser.parse<bool>(prop.name());`
Note, if we try to query TDH_INTYPE_BOOLEAN as BOOL (or any other 4-byte type) function parse() rise another exception "Attempt to read property 'XXX' type BOOLEAN as INT32"
> Fix parsing of boolean type

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/etw.hpp
- krabsetw.nuspec
As [issue #157](https://github.com/microsoft/krabsetw/issues/157) said, there is an error when manage the provider on Microsoft-Windows-Security-Auditing, tested on Windows10 1709, Windows server 2012 R2.
So I handle error code invalid_parameter (87) just the same as the catch for need_to_be_admin_failure (5).
> catch invalid_parameter in register_trace()

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabs/krabs/testing/extended_data_builder.hpp
- krabsetw.nuspec
Including krabsetw from a project that defines "NOMINMAX" would cause a
compilation error due to the absence of the "min" macro. The issue is
fixed by using "std::min<size_t>" instead  of "min". Note that we
explicitly specify the template type in "std::min<size_t>" to avoid a
clash with the "min" macro in the case where "NOMINMAX" is not defined.
Also, check that there is no truncation when casting size_t to USHORT.
Tests: ran all test.
> Replace "min" by "std::min<size_t>" to support NOMINMAX

- Microsoft.O365.Security.Native.ETW/Errors.hpp
- Microsoft.O365.Security.Native.ETW/Testing/RecordBuilder.hpp
- krabs/krabs/errors.hpp
- krabs/krabs/guid.hpp
- krabs/krabs/schema_locator.hpp
- Add CLI exception types for `schema not found` and `unexpected status code`
- Include status code, provider ID, and event record ID in the exception message when possible
> Include record context when handling schema and unexpected errors

- krabs/krabs/etw.hpp
- krabs/krabs/trace.hpp
Some providers need to be configured through ETW's TraceSetInformation
function which we wrap inside trace::set_trace_information to maintain
encapsulation of the trace handle.
Tests: Setup sampling profiling. All tests pass.
See discussion in #171
> Add trace::set_trace_information method

- examples/ManagedExamples/UserTrace007_StackTrace.cs
This example only PR updates the C# call stack sample code with ETW-based call stack module enrichment and symbols for common modules.
Per user request - https://twitter.com/jsecurity101/status/1593355498581016576
I haven't bumped the version number - since no modifications to the libraries were made.
> add call stack enrichment to the C# example

- krabs/krabs/schema.hpp
A schema has the provider GUID available but no way to access it. Having the provider GUID available from a schema enables applications to use the schema directly for GUID comparisons without relying on existing provide_name() string comparisons.
> Add a method to return the provider GUID from a given schema

- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- README.md
- krabsetw.nuspec
1 Update package versions to 4.4.0.
2 Update release notes to inform Windows ARM64 support.
> Update package versions and release notes.

- Microsoft.O365.Security.Native.ETW/AssemblyInfo.cpp
- Microsoft.O365.Security.Native.ETW/EventRecord.hpp
- Microsoft.O365.Security.Native.ETW/IEventRecord.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- examples/ManagedExamples/UserTrace007_StackTrace.cs
- krabs/krabs/schema.hpp
- krabs/krabs/testing/extended_data_builder.hpp
- krabsetw.nuspec
On an x86 application, ULONG_PTR is 4 bytes long, which means it cannot handle 8-byte long kernel addresses used by a 64-bit system.
> Correctly handle kernel addresses in an x86 stack trace

- Microsoft.O365.Security.Native.ETW/AssemblyInfo.cpp
- Microsoft.O365.Security.Native.ETW/EventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/RawProvider.hpp
- O365.Security.Native.ETW.Debug.nuspec
- O365.Security.Native.ETW.nuspec
- krabsetw.nuspec
RawProvider::EventNotification created a new managed object EventRecordMetadata for each EVENT_RECORD it received. Since each provider is single threaded, we should be able to reuse a single allocation by replacing the pointers to the user data in EVENT_RECORD native object on a single EventRecordMetadata before raising the event up to the managed layer.
This change makes the user record and the header pointers in EventRecordMetadata accessible internally so that they can be updated from each EVENT_RECORD received in the RawProvider. RawProvider adds a EventRecordMetadata^ member that gets initialized in the constructor and re-used for each EVENT_RECORD by updating the two pointers each time.
> Only allocate one EventRecordMetadata^ and reuse it for RawProvider events

- Microsoft.O365.Security.Native.ETW/EventRecord.hpp
- Microsoft.O365.Security.Native.ETW/EventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/IEventRecord.hpp
- Microsoft.O365.Security.Native.ETW/IEventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/KernelTrace.hpp
- Microsoft.O365.Security.Native.ETW/UserTrace.hpp
- krabs/krabs/trace.hpp
- krabs/krabs/ut.hpp
Based on https://github.com/microsoft/krabsetw/pull/210
- Add functions to disable MOF/WPP events processing
- Add function to get event type - the logic is reverse-engineered from tdh!TdhGetEventInformation
- Add the corresponding .NET wrapper and supplement what was missing before.
> Add functions to disable MOF/WPP events processing and function to get event type

- Microsoft.O365.Security.Native.ETW/Filtering/Fluent.hpp
- Microsoft.O365.Security.Native.ETW/Testing/RecordBuilder.hpp
- krabs/krabs.hpp
original(.net462): 2473kb
new(.net462): 954kb
> Disable MSIL generation for krabs .NET wrapper native part to significantly reduce binary size

- Microsoft.O365.Security.Native.ETW/Callbacks.hpp
- Microsoft.O365.Security.Native.ETW/EventRecord.hpp
- Microsoft.O365.Security.Native.ETW/EventRecordError.hpp
- Microsoft.O365.Security.Native.ETW/EventRecordMetadata.hpp
- Microsoft.O365.Security.Native.ETW/Filtering/EventFilter.hpp
- Microsoft.O365.Security.Native.ETW/ITrace.hpp
- Microsoft.O365.Security.Native.ETW/KernelProvider.hpp
- Microsoft.O365.Security.Native.ETW/KernelTrace.hpp
- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj
- Microsoft.O365.Security.Native.ETW/Microsoft.O365.Security.Native.ETW.vcxproj.filters
- Microsoft.O365.Security.Native.ETW/Provider.hpp
- Microsoft.O365.Security.Native.ETW/RawProvider.hpp
- Microsoft.O365.Security.Native.ETW/UserTrace.hpp
- examples/ManagedExamples/KernelTrace002.cs
- krabs/krabs/schema_locator.hpp
- krabs/krabs/ut.hpp
- tests/ManagedETWTests/describe_Proxy.cs
1. Unify. NET wrappers of callbacks to simplify logic
2. Add no throw version of get_event_schema and also cache error status
3. Merge the ability of RawProvider to Provider to reduce the fragmentation of code functionality
4. Remove invalid GCHandle usages
5. Use schema_locator.get_event_schema_no_throw in ut::forward_events to avoid exceptions
6. Check status code instead of throw then catch exceptions to gain more performance
7. Also cache EventRecord and EventRecordError objects like EventRecordMetadata to reduce allocations
Closes https://github.com/microsoft/krabsetw/issues/252
Closes https://github.com/microsoft/krabsetw/issues/253
> Unify. NET wrappers of callbacks and more optimizations
